[metadata]
name = mcap2csv
version = 0.1.0
description = Convert ROS2 MCAP bag files to CSV files, one per topic.
author = jjnak
license = LICENSE
readme = README.md

[options]
python_requires = >=3.9
py_modules =
    mcap2csv
    mcap2csv_gui
install_requires =
    mcap-ros2-support
    numpy
    pandas
    PySide6

[options.entry_points]
console_scripts =
    mcap2csv = mcap2csv:main
    mcap2csv-gui = mcap2csv_gui:main